config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#home"
  get "dashboard" => "pages#dashboard"
  get "login" => "sessions#new"
  post "auth" => "sessions#create"
  delete "logout" => "sessions#destroy"

  get "register" => "users#new"
  post "register" => "users#create"
  get "users/stocks" => "users#stocks"

  resources :transactions do
    collection do
      post :deposit
      post :withdraw
      post :transfer
    end
  end

  namespace :stocks do
    get :price
    get :prices
    get :price_all
    get :update_prices
    get :purchase
    post :buy_stock
    get :sell
    post :sell_stock
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :stock_transactions
end

app/controllers/stocks_controller.rb
# frozen_string_literal: true

class StocksController < ApplicationController
  before_action :require_login
  before_action :get_stock_data, only: :prices
  before_action :assign_user_stock, only: :sell
  before_action :assign_stock, only: :purchase

  def price_all
    @stocks = Stock.all
  end

  def prices
    paginated_stocks = paginate(@stocks, params)
    @pagination = paginated_stocks[:pagination]
    @data = paginated_stocks[:data]
  end

  def update_prices
    LatestStockPrice::PriceUpdater.new.perform
    redirect_to stocks_price_all_path, notice: "Prices updated"
  end

  def purchase
    redirect_to stocks_prices_path, notice: "Stock not found" unless @stock

    @transaction = StockTransaction.new(wallet_id: @current_user.wallet.id, stock_id: @stock.id)
  end

  def buy_stock
    @transaction = StockTransaction.new(stock_transaction_params)
    @transaction.wallet_id = @current_user.wallet.id
    @transaction.transaction_type = :buy

    respond_to do |format|
      @transaction.save
      sucess_redirect_with_notice(format, dashboard_path, "Buy Stock Success")
    rescue => e
      error_redirect_with_alert(format, stocks_purchase_path(stock_id: @transaction.stock_id), e.message)
    end
  end

  def sell
    redirect_to stocks_prices_path, notice: "Stock not found" unless @stock

    @transaction = StockTransaction.new(wallet_id: @current_user.wallet.id, stock_id: @stock[:id])
  end

  def sell_stock
    @transaction = StockTransaction.new(stock_transaction_params)
    @transaction.wallet_id = @current_user.wallet.id
    @transaction.transaction_type = :sell

    respond_to do |format|
      @transaction.save
      sucess_redirect_with_notice(format, dashboard_path, "Sell Stock Success")
    rescue => e
      error_redirect_with_alert(format, stocks_sell_path(stock: @transaction.stock.identifier), e.message)
    end
  end



  private

  def get_stock_data
    @stocks = Stock.all
    search_query = params[:stock]
    @stocks = @stocks.where("identifier LIKE ? OR symbol LIKE ?", "%#{search_query}%", "%#{search_query}%") if search_query.present?
  end

  def assign_stock
    @stock = Stock.find_by(id: params[:stock_id])
  end

  def assign_user_stock
    stocks = Stocks::ListService.new(user: @current_user).perform
    @stock = stocks.select { |s| s[:stock] == params[:stock] }.first
    redirect_to users_stocks_path, notice: "Stock not found" unless @stock
  end

  def stock_transaction_params
    params.require(:stock_transaction).permit(:stock_id, :quantity)
  end
end

app/views/stocks/price_all.html.slim
.ui.container
  .ui.secondary.menu
    .item
      = link_to "Dashboard", dashboard_path
    .item
      = link_to "Stock Prices", stocks_prices_path
    .item
      | Stock Price All
    .right.menu
      .item
        .ui.icon.input
          input[type="text" placeholder="Search..." id="search"]
          i.search.link.icon
      a.ui.item
        = link_to "Logout", logout_path, method: :delete, class: "ui inverted red button", data: { "turbo-method": :delete }
  h1.ui.header.center.aligned
    | All Stock Price
  .ui.grid.ui.equal.height.grid
    .ui.row.summaries
      .ui.cards.centered
        - @stocks.each do |stock|
          .card
            .content.stockheader
              = "#{stock.identifier} "
              = "(#{stock.symbol})" 
            .content
              h4.ui.sub.header
                | Price
              .ui.small.feed
                .event
                  .content
                    .summary
                      a
                        | Change     : 
                      = stock.change
                .event
                  .content
                    .summary
                      a
                        | Day High   : 
                      = stock.day_high
                .event
                  .content
                    .summary
                      a
                        | Day Low    : 
                      = stock.day_low
                .event
                  .content
                    .summary
                      a
                        | Last Price : 
                      = stock.last_price
                .event
                  .content
                    .summary
                      a
                        | Last Updated : 
                      = stock.last_update_time.strftime("%B %d, %Y %H:%M:%S")

  br
  br
  = link_to 'Update All Prices', stocks_update_prices_path, class: 'ui blue small button', method: :get

app/views/stocks/prices.html.slim
.ui.container
  .ui.secondary.menu
    .item
      = link_to "Dashboard", dashboard_path
    .item
      | Stock Prices
    .item
      = link_to "Stock Prices All", stocks_price_all_path
    .right.menu
      .item
        .ui.icon.input
          input[type="text" placeholder="Search..." id="search"]
          i.search.link.icon#search
      a.ui.item
        = link_to "Logout", logout_path, method: :delete, class: "ui inverted red button", data: { "turbo-method": :delete }
  h1.ui.header.center.aligned
    | Stock Prices 
    = "Page #{@pagination[:current]}"
  .ui.grid.ui.equal.height.grid
    .ui.row.summaries
      .ui.cards.centered
        - if @data.blank?
          | NO STOCK FOUND
        - else
          - @data.each do |stock|
            .card
              .content.stockheader
                = "#{stock.identifier} "
                = "(#{stock.symbol})" 
              .content
                h4.ui.sub.header
                  | Price
                .ui.small.feed
                  .event
                    .content
                      .summary
                        a
                          | Change     : 
                        = stock.change
                  .event
                    .content
                      .summary
                        a
                          | Day High   : 
                        = stock.day_high
                  .event
                    .content
                      .summary
                        a
                          | Day Low    : 
                        = stock.day_low
                  .event
                    .content
                      .summary
                        a
                          | Last Price : 
                        = stock.last_price
                  .event
                    .content
                      .summary
                        a
                          | Last Updated : 
                        = stock.last_update_time.strftime("%B %d, %Y %H:%M:%S")

                  - if @current_user
                    = link_to 'Buy This Stock', stocks_purchase_path(stock_id: stock.id), class: 'ui blue small button', method: :post

  - if !@data.blank?
    .ui.pagination.menu style="margin-top: 10px"
      - if @pagination[:current] == 1
        a.active.item
          |  1 
      - else
        a.item href="#{stocks_prices_path(page: 1)}"
          |  1 
      - if @pagination[:current] > 4
        .disabled.item
          |  ... 
      - for page in (@pagination[:current] - 2)..(@pagination[:current] + 2)
        - if page > 1 && page < @pagination[:last_page]
          - if page == @pagination[:current]
            a.active.item
              |  #{page} 
          - else
            a.item href="#{stocks_prices_path(page: page, stock: params[:stock])}"
              |  #{page} 
      - if @pagination[:current] < @pagination[:last_page] - 3
        .disabled.item
      - if @pagination[:current] == @pagination[:last_page]
        a.active.item
          |  #{@pagination[:last_page]} 
      - else
        a.item href="#{stocks_prices_path(page: @pagination[:last_page], stock: params[:stock])}"
          |  #{@pagination[:last_page]} 
  br
  br
  = link_to 'Update All Prices', stocks_update_prices_path, class: 'ui blue small button', method: :get

app/views/stocks/purchase.html.slim
.ui.container
  .ui.secondary.menu
    .item
      = link_to "Dashboard", dashboard_path
    .item
      = link_to "Stock Prices", stocks_prices_path
    .item
      = link_to "Stock Prices All", stocks_price_all_path
    .right.menu
      .item
        .ui.icon.input
          input[type="text" placeholder="Search..." id="search"]
          i.search.link.icon#search
      a.ui.item
        = link_to "Logout", logout_path, method: :delete, class: "ui inverted red button", data: { "turbo-method": :delete }

  h1.ui.header.center.aligned
    | Buy Stock
  .ui.grid
    .ui.row
      .column
        .ui.fluid.card
          .content
            .header
              h3
              = "#{@stock.identifier} (#{@stock.symbol})"
              .content
                .ui.small.feed
                  .event
                    .content
                      .summary
                        = form_for @transaction, url: url_for(controller: 'stocks', action: 'buy_stock'), method: 'post', html: { class: "ui form" } do |f|
                          .two.fields
                            .field
                              label
                                | Amount
                            .field
                              = f.number_field :quantity
                          .two.fields
                            .field
                              label
                                | Current Price
                            .field
                              = @stock.last_price
                              = f.hidden_field :stock_id, value: @transaction.stock_id
                          = f.submit "Buy", name: "Buy", class: "ui blue button"

  

app/views/stocks/sell.html.slim
.ui.container
  .ui.secondary.menu
    .item
      = link_to "Dashboard", dashboard_path
    .item
      = link_to "Stock Prices", stocks_prices_path
    .item
      = link_to "Stock Prices All", stocks_price_all_path
    .right.menu
      .item
        .ui.icon.input
          input[type="text" placeholder="Search..." id="search"]
          i.search.link.icon#search
      a.ui.item
        = link_to "Logout", logout_path, method: :delete, class: "ui inverted red button", data: { "turbo-method": :delete }

  h1.ui.header.center.aligned
    | Sell Stock
  .ui.grid
    .ui.row
      .column
        .ui.fluid.card
          .content
            .header
              h3
              = "#{@stock[:stock]} (#{@stock[:symbol]})"
              .content
                .ui.small.feed
                  .event
                    .content
                      .summary
                        = form_for @transaction, url: url_for(controller: 'stocks', action: 'sell_stock'), method: 'post', html: { class: "ui form" } do |f|
                          br
                          .two.fields
                            .field
                              label
                                | Amount owned
                            .field
                              = @stock[:quantity]
                          .two.fields
                            .field
                              label
                                | Amount to sell
                            .field
                              = f.number_field :quantity
                          .two.fields
                            .field
                              label
                                | Current Price
                            .field
                              = Stock.find(@stock[:id]).last_price
                              = f.hidden_field :stock_id, value: @stock[:id]
                          = f.submit "Sell", name: "Sell", class: "ui blue button"

  