config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#home"
  get "dashboard" => "pages#dashboard"
  get "login" => "sessions#new"
  post "auth" => "sessions#create"
  delete "logout" => "sessions#destroy"

  get "register" => "users#new"
  post "register" => "users#create"
  get "users/stocks" => "users#stocks"

  resources :transactions do
    collection do
      post :deposit
      post :withdraw
      post :transfer
    end
  end

  namespace :stocks do
    get :price
    get :prices
    get :price_all
    get :update_prices
    get :purchase
    post :buy_stock
    get :sell
    post :sell_stock
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :wallet
  has_many :stock_transactions
  has_many :user_transactions

  attr_accessor :password

  before_save :digest_password
  before_save :assign_wallet

  INITIAL_BALANCE = 50_000

  validates :username, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def digest_password
    self.password_digest = Digest::SHA2.hexdigest(password)
  end

  def assign_wallet
    return unless new_record?

    self.user_transactions.build({
      transaction_type: :receive,
      balance: INITIAL_BALANCE
    })
    self.build_wallet(balance: INITIAL_BALANCE)
  end

  def wallet_balance
    wallet.balance
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: :new
  before_action :require_login, only: :stocks

  def new
    @user = User.new
  end

  def create
    respond_to do |format|
      begin
        @user = Auth::RegisterService.new(params: params[:user]).perform
        sucess_redirect_with_notice(format, login_path, "User was successfully created. Please log in")
      rescue => e
        error_redirect_with_alert(format, register_path, e.message)
      end
    end
  end

  def index
    @users = User.all
  end

  def stocks
    @stocks = Stocks::ListService.new(user: @current_user).perform
    paginated_stocks = paginate(@stocks, params)
    @pagination = paginated_stocks[:pagination]
  end
end

app/views/users/new.html.slim
.ui.container
  h1.ui.header.center.aligned
    | Register
  = form_for @user, url: url_for(controller: 'users', action: 'create', method: :post), html: {class: "ui form"} do |f|
    .field
      = f.label :username, 'Username'
      = f.text_field :username
    .field
      = f.label :email, 'Email'
      = f.text_field :email
    .field
      = f.label :password, 'Password'
      = f.password_field :password
    button.ui.button[type="submit"]
      | Register
  = link_to 'Already have an account? Click here to login', login_path

app/views/users/stocks.html.slim
.ui.container
  .ui.secondary.menu
    .item
      = link_to "Dashboard", dashboard_path
    .item
      | Stock Prices
    .item
      = link_to "Stock Prices All", stocks_price_all_path
    .right.menu
      .item
        .ui.icon.input
          input[type="text" placeholder="Search..." id="search"]
          i.search.link.icon#search
      a.ui.item
        = link_to "Logout", logout_path, method: :delete, class: "ui inverted red button", data: { "turbo-method": :delete }
  h1.ui.header.center.aligned
    | Stock Prices 
    = "Page #{@pagination[:current]}"
  .ui.grid.ui.equal.height.grid
    .ui.row.summaries
      .ui.cards.centered
        - if @stocks.blank?
          | NO STOCK FOUND
        - else
          - @stocks.each do |stock|
            - next unless stock[:quantity].positive?
            .card
              .content.stockheader
                = "#{stock[:stock]} "
                = "(#{stock[:symbol]})" 
              .content
                h4.ui.sub.header
                  | Detail
                .ui.small.feed
                  .event
                    .content
                      .summary
                        a
                          | Quantity     : 
                        = stock[:quantity]
                  .event
                    .content
                      .summary
                        a
                          | Total   : 
                        = stock[:balance].round(2)
                  = link_to 'Sell This Stock', stocks_sell_path(stock: stock[:stock]), class: 'ui blue small button', method: :get

  - if !@stocks.blank?
    .ui.pagination.menu style="margin-top: 10px"
      - if @pagination[:current] == 1
        a.active.item
          |  1 
      - else
        a.item href="#{stocks_prices_path(page: 1)}"
          |  1 
      - if @pagination[:current] > 4
        .disabled.item
          |  ... 
      - for page in (@pagination[:current] - 2)..(@pagination[:current] + 2)
        - if page > 1 && page < @pagination[:last_page]
          - if page == @pagination[:current]
            a.active.item
              |  #{page} 
          - else
            a.item href="#{stocks_prices_path(page: page, stock: params[:stock])}"
              |  #{page} 
      - if @pagination[:current] < @pagination[:last_page] - 3
        .disabled.item
      - if @pagination[:current] == @pagination[:last_page]
        a.active.item
          |  #{@pagination[:last_page]} 
      - else
        a.item href="#{stocks_prices_path(page: @pagination[:last_page], stock: params[:stock])}"
          |  #{@pagination[:last_page]} 