config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#home"
  get "dashboard" => "pages#dashboard"
  get "login" => "sessions#new"
  post "auth" => "sessions#create"
  delete "logout" => "sessions#destroy"

  get "register" => "users#new"
  post "register" => "users#create"
  get "users/stocks" => "users#stocks"

  resources :transactions do
    collection do
      post :deposit
      post :withdraw
      post :transfer
    end
  end

  namespace :stocks do
    get :price
    get :prices
    get :price_all
    get :update_prices
    get :purchase
    post :buy_stock
    get :sell
    post :sell_stock
  end
end

app/views/pages/dashboard.html.slim
.ui.container
  .ui.secondary.menu
    .item
      |  Dashboard 
    .item
      = link_to "Stock Prices", stocks_prices_path
    .item
      = link_to "Stock Price All", stocks_price_all_path
    .right.menu
      .item
        .ui.icon.input
          input[type="text" placeholder="Search..." id="search"]
          i.search.link.icon
      a.ui.item
        = link_to "Logout", logout_path, method: :delete, class: "ui inverted red button", data: { "turbo-method": :delete }
  h1.ui.header.center.aligned
    | Dashboard
  .ui.grid.ui.equal.height.grid
    .ui.row.summaries
      .ui.cards.centered
        .card
          .content
            .header
              | User Summary (
              = @current_user.username
              | )
          .content
            h4.ui.sub.header
              | Activities
            .ui.small.feed
              .event
                .content
                  .summary
                    a
                      | Debit (Deposit)              : 
                    = @debit.round(2)
              .event
                .content
                  .summary
                    a
                      | Credit (Withdrawal)            : 
                    = @credit.round(2)
              .event
                .content
                  .summary
                    a
                      | Current Balance    : 
                    = @current_user.wallet_balance.round(2) || 0
        .card
          .content
            .header
              | Stock Summary
          .content
            h4.ui.sub.header
              | Details
            .ui.small.feed
              .event
                .content
                  .summary
                    a
                      | Stock Owned   : 
                    = @stocks.size
              .event
                .content
                  .summary
                    a
                      | Stock Value   : 
                    = @stocks.sum { |s| s[:balance].round(2)}
              .event
                .content
                  .summary
                    a
                    =  link_to "Click here to see your stocks", users_stocks_path
      br
    .ui.row
      .column
        .ui.fluid.card
          .content
            .header
              | Create Deposit
          .content
            .ui.small.feed
              .event
                .content
                  .summary
                    = form_for @transaction, url: url_for(controller: 'transactions', action: 'deposit'), method: 'post', html: { class: "ui form" } do |f|
                      .two.fields
                        .field(style="text-align: center; align-content: center")
                          label
                            | Amount
                        .field
                          input[type="text" name="amount" placeholder="Deposit Amount"]
                        = f.submit "Deposit", name: "deposit", class: "ui blue button", style: "position: absolute; bottom: 0; right: 0;"
                      
    .ui.row
      .column
        .ui.fluid.card
          .content
            .header
              | Create Withdrawal
          .content
            .ui.small.feed
              .event
                .content
                  .summary
                    = form_for @transaction, url: url_for(controller: 'transactions', action: 'withdraw'), method: 'post', html: { class: "ui form" } do |f|
                      .two.fields
                        .field(style="text-align: center; align-content: center")
                          label
                            | Amount
                        .field
                          input[type="text" name="amount" placeholder="Withdraw Amount"]
                        = f.submit "Withdraw", name: "withdraw", class: "ui blue button", style: "position: absolute; bottom: 0; right: 0;"

    .ui.row
      .column
        .ui.fluid.card
          .content
            .header
              | Transfer to Another User
          .content
            .ui.small.feed
              .event
                .content
                  .summary
                    = form_for @transaction, url: url_for(controller: 'transactions', action: 'transfer'), method: 'post', html: { class: "ui form" } do |f|
                      .four.columns
                        .two.fields.row
                          .field(style="text-align: center; align-content: center")
                            label
                              | Username
                          .field
                            input[type="text" name="username" placeholder="Username to transfer"]
                        .two.fields.row
                          .field(style="text-align: center; align-content: center")
                            label
                              | Amount
                          .field
                            input[type="text" name="amount" placeholder="Amount"]

                        = f.submit "Transfer", name: "deposit", class: "ui blue button", style: "position: absolute; bottom: 0; right: 0;"
    .ui.row

app/views/pages/home.html.slim
.ui.middle.aligned.center.aligned.grid
  .column
    .ui.equal.width.form
      .field
        label
          | Username
        input[type="text" placeholder="Username"]
      .field
        label
          | Password
        input[type="password"]
      | 